### ISSUE TITLE
failed to open stream: No such file or directory in file: /htdocs/cacti/lib/functions.php on line: 5198

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_cycle#17] opened 2020-04-06 20:53 UTC
Cacti 1.2.11
Cycle dev 4.2
```

2020/04/06 16:51:07 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/cycle/cycle.php[54]:cycle(), /plugins/cycle/cycle.php[151]:get_md5_include_js(), /lib/functions.php[5217]:get_md5_hash(), /lib/functions.php[5198]:md5_file(), CactiErrorHandler())
--
2020/04/06 16:51:07 - ERROR PHP WARNING: md5_file(/var/www/localhost/htdocs/cacti/lib/../plugin/cycle/cycle.js): failed to open stream: No such file or directory in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 5198

```

**Comment by netniV** [comment] 2020-04-06 21:47
This suggests you haven’t named the plugin folder correctly.

**Comment by jdcoats** [comment] 2020-04-06 23:16
I love how quick you are to respond but what part of plugins/cycle/cycle.php is incorrect?
If incorrect the plugin wouldn’t install and the setting wouldn’t be available.

**Comment by netniV** [comment] 2020-04-06 23:37
Cycle.js is in the same folder as the php

**Comment by jdcoats** [comment] 2020-04-06 23:45
and? Thats the way it is in dev.
I think the change from 13hrs ago broke it. not sure....

**Comment by netniV** [comment] 2020-04-06 23:52
Then the only reason it wouldn’t be found is either sellinix or permissions if that path is correct which it looks to be. Have you checked if?

**Comment by jdcoats** [comment] 2020-04-06 23:53
https://github.com/Cacti/plugin_cycle/commit/e0fb5d919a2cbc3b042ee9ac60dd58677ae6f158

**Comment by jdcoats** [comment] 2020-04-06 23:54
no selinux

```
 /var/www/localhost/htdocs/cacti/plugins/cycle # ls -al
total 101
drwxr-xr-x  5 apache apache   472 Apr  6 16:44 .
drwxr-xr-x 12 apache apache   336 Apr  6 16:44 ..
-rwxr-xr-x  1 apache apache  9471 Apr  6 16:44 cycle.js
-rw-r--r--  1 apache apache 12944 Apr  6 16:44 cycle.php
-rw-r--r--  1 apache apache 15933 Apr  6 16:44 functions.php
drwxr-xr-x  3 apache apache   112 Apr  6 16:44 .github
-rw-r--r--  1 apache apache    16 Apr  6 16:44 .gitignore
drwxr-xr-x  2 apache apache   152 Apr  6 16:44 images
-rw-r--r--  1 apache apache  1588 Apr  6 16:44 index.php
-rw-r--r--  1 apache apache   234 Apr  6 16:44 INFO
-rw-r--r--  1 apache apache 15171 Apr  6 16:44 LICENSE
drwxr-xr-x  4 apache apache   168 Apr  6 16:44 locales
-rw-r--r--  1 apache apache    60 Apr  6 16:44 .mdlrc
-rw-r--r--  1 apache apache   577 Apr  6 16:44 .mdl_style.rb
-rw-r--r--  1 apache apache  4056 Apr  6 16:44 README.md
-rw-r--r--  1 apache apache 11649 Apr  6 16:44 setup.php
-rw-r--r--  1 apache apache  1052 Apr  6 16:44 .travis.yml
```

**Comment by jdcoats** [comment] 2020-04-06 23:56
/me points back at https://github.com/Cacti/plugin_cycle/commit/e0fb5d919a2cbc3b042ee9ac60dd58677ae6f158

		print get_md5_include_js('plugin/cycle/cycle.js'     <<<< /s/plugin/plugins

**Comment by netniV** [comment] 2020-04-06 23:59
And there you have it.  A daft typo by me, that was correct on my work system were I wrote the original patch to try it out.  Since it was so small, i reproduced it with an error ;)

I was just coming back to the laptop to see if I could spot anything as on my phone answers were kept short and I couldn't see much wrong.

**Comment by netniV** [comment] 2020-04-07 00:01
This should now be resolved in f347f5c.  Since it was within the release itself, I haven't done another change entry.  Thanks for your patience.

**Comment by jdcoats** [comment] 2020-04-07 00:01
fixed on my side, thanks for helping me to look and fix for myself :), I learn something new every day

**Comment by netniV** [comment] 2020-04-07 00:03
I didn't really do much but look at my phone screen (until I came up to apply the fix).  Glad it is a quick fix though, I was starting to wonder why it wouldn't work when it did for me.

**Comment by jdcoats** [comment] 2020-04-07 00:03
thanks for all you guys are doing. 1.2.11 is fabulous, very stable and all plugins are working great at this point in time. All safe healthy and safe in this time...

**Closed as completed by netniV** 2020-04-07 00:03 UTC
Labels: bug, resolved, confirmed
