### ISSUE TITLE
Countdown timer does not stop when requested

### ISSUE THREAD

**Issue by jayaich** [Cacti/plugin_cycle#14] opened 2019-03-22 14:39 UTC
Hello,

Using the latest code it seems that if I am looking at a cycle page with graphs and click on the 'Stop' button, the clock continues to count down. In fact it speeds up, as far as I can tell, to running twice as fast. So the graphs update every 30 seconds instead of every minute. Clicking on the 'Start' button the clock continues, but again seems to speed up (probably to about 3 or 4 times as fast). Clicking on 'Stop' again does not stop the clock.
The button itself correctly changes to showing 'Stop' or 'Start' as required.

**Comment by netniV** [comment] 2019-03-22 14:41
This actually sounds like it is being called more than once.  I bet if you were to click a few times, it would go even faster!  I'll have to rectify tonight.  Just revert back to the previous version for now until it's corrected.

**Comment by bmfmancini** [comment] 2019-09-19 16:33
Hey @netniV  this is still on going was this fixed ?

**Comment by netniV** [comment] 2019-09-19 17:58
Nope. No fixie, yet.

**Comment by netniV** [comment] 2019-09-19 22:14
Should now be sorted though.

**Comment by jayaich** [comment] 2019-10-07 17:09
Sorry for the delay in testing this, however it seems that the problem still exists.
I disabled and uninstalled the plugin via the Cacti console. Installed the new code (downloaded as a zip file), and re-enabled it.
I also cleared the browser cache, and then shut the browser down completely.
I also restarted Apache just to see if that would help.
Sorry to say, but the problem is still there.

**Comment by netniV** [comment] 2019-10-07 17:33
I was able to reproduce it until the latest push I did last week.  I’m no longer able to do so.  If you are able to do so consistently, can you post a screen2gif or gifcam of it in action? Also, can you run an md5 against the plugin files so I can do a quick check to make sure they are the same.

**Comment by jayaich** [comment] 2019-10-08 10:43
Here are the md5 checksums for the files. I'm still working on getting the screenshot/animation together (something I've not done before so a bit new).

366484f173a093972ed45032e62c6884  INFO
3178b603d6560dc009468f671919776f  LICENSE
64c0e53f32d6c5f4653f8f3d420da07d  README.md
45bd5661a52c97a94ef5ea238bb2c957  cycle.js
4ac81f51a2308b4276e302c1b1cb8d41  cycle.php
1e809294a1a1e8bcb5a6145c404184c2  functions.php
917c58295500690565d57664a32f0bed  index.php
be88fe8a83c9efe0bb22e3c5826b9970  setup.php

**Comment by jayaich** [comment] 2019-10-08 11:43
Here is an animated gif of the problem. Watching the timer countdown, clicking on the start/stop button makes no difference. As the timer reaches below 20 seconds it can easily be seen that the timer has speeded up.

![Peek-2019-10-08-12-27](https://user-images.githubusercontent.com/6230023/66392946-30ec4680-e9c9-11e9-98d8-63a27aff8fe1.gif)

**Comment by netniV** [comment] 2019-10-08 22:57
That still seems like the original issue before I adjusted it.  Can you make sure that the cycle.js has changes such as:
```diff
 function refreshTime() {
        ltime++
        $('#countdown').html(formattime(time));
-       if (time == 0) {
-               time=rtime/1000+1;
-               loadGraphs(nextid);
-       }
+
+       if (time == 0)
+               getNext();
+
        time=time-1
 }
```

You can see the full list of changes in f1925df

**Comment by jayaich** [comment] 2019-10-08 23:22
Yes, cycle.js does have those changes.
I went through the commit changes and checked the relevant files to make sure that they did include the changes.

**Comment by netniV** [comment] 2019-10-08 23:35
And there are no browser errors?

**Comment by jayaich** [comment] 2019-10-09 09:51
Ah, sorry yes there are, I didn't check.  The browser console shows:

> jQuery.Deferred exception: timerID is not defined @https://cacti.tis.plymouth.ac.uk/cacti/index.php line 111 > scriptElement:41:4
> mightThrow@https://cacti.tis.plymouth.ac.uk/cacti/include
> /js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:3534:29
> resolve/</process<@https://cacti.tis.plymouth.ac.uk/cacti/include
> /js/jquery.js?2f0d15c70b7e652d5d61ed4032eb44af:3602:12
>  undefined
>
> ReferenceError: timerID is not defined

**Comment by netniV** [comment] 2019-10-09 12:05
Well, that's a strange one given that the global variable `timerID` is defined at the very start of the `cycle.js` script as being null.  It then gets updated by setInterval()'s return value in `startTime()` to be clear by clearInterval() in `stopTime()`.

However, I did notice that the inline JS which links the buttons to functions was calling clearInterval() itself, so I've removed that and made sure that stopTime() is called within applyFilter() and clearFilter().

Give that a try and see where we are.

**Comment by jayaich** [comment] 2019-10-09 12:20
Thanks for that. Still not working.
However, the browser console error appears again but refers to 'stopTime' not being defined now.

**Comment by netniV** [comment] 2019-10-09 17:37
Hmm, that sounds like the main cycle.js isn't being included, can you check the network tab to make sure it is?

**Comment by netniV** [comment] 2019-10-09 17:41
Also, may sure that your cacti core's config.php has the correct url_path defined...

**Comment by jayaich** [comment] 2019-10-10 10:05
On Wed, 2019-10-09 at 10:37 -0700, Mark Brugnoli-Vinten wrote:
> Hmm, that sounds like the main cycle.js isn't being included, can you check
> the network tab to make sure it is?
>
Yes it is being included. The request headers show:

=======
Request URL:https://cacti.tis.plymouth.ac.uk/cacti/plugins/cycle/cycle.js
Request method:GET
Remote address:10.121.16.10:443
Status code:200
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
=======

--
John Horne | Senior Operations Analyst | Technology and Information Services
University of Plymouth | Drake Circus | Plymouth | Devon | PL4 8AA | UK
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by jayaich** [comment] 2019-10-10 10:12
> Also, may sure that your cacti core's config.php has the correct url_path defined...

It does. (Although I would have expected a load of other problems if it wasn't correct.)

**Comment by jayaich** [comment] 2019-10-10 16:12
I have been looking into this a bit this afternoon, and found 2 things:

1) In cycle.js (line 24) it says:
`var timerID = null`
if I change this to just `var timerID` then the stop/start buttons work as expected. The timer stops and starts whenever the relevant button is clicked. The timer now correctly counts down in 1 second intervals regardless of how many times it is stopped/started.
2) The web console error messages are caused by the function calls in cycle.php (line 380 onwards):
`stopTime();`
`startTime();`
`newGraph();`
If I comment these out the errors go, but the initial cycle web page is not then set up quite right.
Looking at the web page source I can see that there is a `</script>.../cycle.js</script>` line, and then further down another script section where the above calls are located. In that respect I see no reason why the errors should appear unless maybe there is some sort of scoping issue between php and javascript.

**Comment by netniV** [comment] 2019-10-10 18:07
So, the Javascript that is part of the header include, is globally scoped since it is in the main code.  The code within cycle.php is part of JQuery's `$()` document ready function, so anything defined there would be out of scope of the cycle.js, but we are using the global functions from within the smaller scope so they should be available.  I did wonder if the variable was maybe not present that would cause an issue, so limited it to the function calls.

I'll give it some testing and see what I can see/prove.

**Comment by netniV** [comment] 2019-10-10 18:10
The NULL value, seems to be incorrect as it looks like its making the setInterval()/clearInterval() calls believe that it's been defined, rather than set to undefined.  I'll add that in as a fix.

**Comment by netniV** [comment] 2019-10-10 19:02
Actually, I've decided to put that back and improve our functions.  Basically, stopTime() and startTime() should be available and has been in my testing with Safari, Firefox and Chrome.  I have improved those functions as well so they will only attempt to start or stop a timer if necessary, plus I made a few other functions correctly start/stop the timer too whilst loading graphs.

**Comment by jayaich** [comment] 2019-10-17 11:52
Using the latest code/commits, this seems to be working fine.
Please feel free to close the issue if you have no further changes for it.

**Closed as completed** 2019-10-17 22:46 UTC
Labels: bug, resolved
